Chat:
    # Format chat colours that have $s or &s
    FormatChatColourCodes: false
    
    # If filled in, display this message to Players that log in. Accepts colours ($ or &).
    MOTD:
      - ""
      
    # Should DECore control login/logout messages (such as x logged in formatted in their rank; or x was autokicked by Minecraft for flying) 
    UseLoginLogoutMessages: true
    
Chests:
    # Should DECore allow players to access covered single chests?
    UseCoveredSingleChests: true
        
    # Should DECore allow players to access covered double chests?
    UseCoveredDoubleChests: true
    
Commands:
    # Use /inv [player] to check a player's inventory
    UseCheckInventoryCommand: true
    
    # Use /clear [player] to clear your/player's inventory
    UseClearInventoryCommand: true
    
    # Should we use /adventure [player], /creative [player], /survival [player] to send /gamemode [player] <0/1/2> as if the player typed it?
    # Note that player argument is optional, and it will default to the player typing the command if not specified.
    UseGameModeShortcuts: true
    
    # Use /chunk [radius] to resend chunks
    UseResendChunkCommand: true
    
    # Use /spawn to teleport to spawn
    UseSpawnCommand: true
   
    # Override Minecraft's /tp to allow for autocompletion of names and omission of player's name.
    UseTPCommand: true
    
    # Use /tpall [world|*] to teleport everyone in world|server to your location
    UseTPAllCommand: true
    
    # Use /tploc to teleport to locations
    UseTPLocCommand: true
    
    # Use /vanish to remove Entity instance and become invisible
    UseVanishCommand: true
   
Flags:
    # Enable/Disable the flags system
    UseFlagsSystem: true
    
    # Number of flags until a Guest is banned
    FlagsToBan: 3
        
GuestSpawnLocation:
    # If filled in, Guests will spawn here instead of the main spawn.
    World:
        X: 0
        Y: 0
        Z: 0    

Mysql:
    # Mysql URL in form jdbc:mysql://<address>. e.g. 'jdbc:mysql://localhost/tables'
    URL: ''
    # The table's name. e.g. 'ATable'
    Tablename: '' 
    # Table login details
    Username: ''
    Password: ''
    
Plugin:
    # Turn Debugging mode on?
    Debugging: false   

Promotions:
    # Promote players to Veterans
    PromoteToVeterans: true
    
    # After how many hours of play time?
    PromoteToVeteransTimeInHours: 72
    
Protections:
    # Disallow helpful throwing potions to be thrown or interacted with
    BanHelpfulThowingPotions: false
    
    # Disallow hostile throwing potions to be thrown or interacted with
    BanHostileThowingPotions: false
    
    # Block creeper environment damage
    CreeperProtect: true
    
    # Block enderman environment damage
    EndermenProtect: true
    
    # Should sheep ALWAYS regrow their wool?
    ForceSheepWoolRegrowth: true
    
    # Lightning caused by DECore and plugins are not effects and will do explosion damage
    LightningIsReal: false
    
Server:
    # The broadcast range of Death Messages. 0 Turns OFF messages. -1 Broadcasts to the server. -2 Broadcasts to the world.
    DeathMessageBroadcastRange: -2
    
    # Disable "Server can't keep up" messages on console
    DisableCantKeepUpMessages: true
    
    # Moderated mode forces server players under junior moderator offline if no jmod+ is present
    Moderated: false 
    
    # Show this message if a Player can't get on because they aren't whitelisted
    NotWhiteListedMessage: Not whitelisted. www.deviantevil.net
    
    # World boarder to stop events and players from wondering outside the area. 
    # Associated permissions:
    #   de.worldboarder.allow.*  |  de.worldboarder.allow.x  |  de.worldboarder.allow.y  |  de.worldboarder.allow.z 
    # Format:
    # WorldBoarders:
    #     <worldname>:
    #         XMAX: <Maximum x co-ordinate players are allowed up to.>
    #         XMIN: <Minimum x co-ordinate players are allowed up to.>
    #         YMAX: <Maximum y co-ordinate players are allowed up to.>
    #         YMIN: <Minimum y co-ordinate players are allowed up to.>
    #         ZMAX: <Maximum z co-ordinate players are allowed up to.>
    #         ZMIN: <Minimum z co-ordinate players are allowed up to.>
    WorldBoarders: 
        world:
            XMAX: 2500
            XMIN: -2500
            YMAX: 256
            YMIN: 0
            ZMAX: 2500
            ZMIN: -2500
    # Players that have access to /de opme and other DECore commands without permissions.
    DECoreOpsCanOpSelf:
      - Heifinator
      - kjhf
      - GordyKnows

Vote:
# Variables are %dep, %player, %reward, %times
# %dep = DEPoints received (if any)
# %player = the player who voted
# %reward = the creds they received (times * Reward)
# %times = the number of times the player has voted since they last logged on

    # The message to broadcasting when a player has voted. An empty string ("") disables this. 
    BroadcastMessage: "%player has just earned %reward by voting %times times! Have you voted today? http://deviantevil.net"
    DEPChance: 1
    DEPReward: 1
    Reward: 50
    
    # The message to thank a player for voting. An empty string ("") disables this.
    ThankYouMessage: "Thank you %player for voting for us %times times since you logged in! You have been rewarded %rewardc!"
    
    # If DEPoints are rewarded this message is also sent.
    ThankYouMessageDEP: "Thanks %player, your vote earned you %dep DEP!"
    
Vouching:
    # Enable/Disable the vouching system
    UseVouchingSystem: true
    
    # Number of vouches until a Guest is promoted to Member
    VouchesToMember: 3